version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  reviewers:
  - brenetic
  - mattempty
  - njseeto
- package-ecosystem: docker
  directory: "/docker/api"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  reviewers:
  - brenetic
  - mattempty
  - njseeto
- package-ecosystem: docker
  directory: "/docker/workers"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  reviewers:
  - brenetic
  - mattempty
  - njseeto
