version: 2
jobs:
  test:
    working_directory: ~/circle
    docker:
      - image: ministryofjustice/ruby:2.5.1
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: root
          DATABASE_URL: postgresql://root@localhost/fb-submitter_test
      - image: circleci/postgres:10.6-alpine-ram
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle-test_test
    steps:
      - checkout
      - run:
          name: bundle install
          command: 'bundle install --deployment --jobs=2 --retry 3 --without development'
      - run:
          name: setup database
          command: 'RAILS_ENV=test bundle exec rake db:create db:schema:load'
      - run:
          name: test
          command: 'bundle exec rspec'
  build:
    working_directory: ~/circle/git/fb-submitter
    docker:
      - image: asmega/fb-builder:latest
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "bd:17:68:ef:38:5e:72:09:06:df:e1:d4:a4:2e:64:94"
      - run:
          name: checkout fb-submitter-deploy
          command: "GIT_SSH_COMMAND='ssh -v -i ~/.ssh/id_rsa_bd1768ef385e720906dfe1d4a42e6494 -o \"IdentitiesOnly=yes\"' git clone git@github.com:ministryofjustice/fb-submitter-deploy.git ~/circle/git/fb-submitter-deploy"
      - run:
          name: npm install
          command: 'npm install'
      - setup_remote_docker
      - run:
          name: KUBE_CERTIFICATE_AUTHORITY to disk
          command: 'echo -n "$KUBE_CERTIFICATE_AUTHORITY" | base64 -d > /root/circle/.kube_certificate_authority'
      - run:
          name: kubectl configure cluster
          command: 'kubectl config set-cluster "$KUBE_CLUSTER" --certificate-authority="/root/circle/.kube_certificate_authority" --server="$KUBE_SERVER"'
      - run:
          name: kubectl configure credentials
          command: 'kubectl config set-credentials "circleci" --token="$KUBE_TOKEN"'
      - run:
          name: kubectl configure context
          command: 'kubectl config set-context "circleci" --cluster="$KUBE_CLUSTER" --user="circleci" --namespace="formbuilder-repos"'
      - run:
          name: kubectl use circleci context
          command: 'kubectl config use-context circleci'
      - run:
          name: build and push docker images
          command: 'cd ~/circle/git/fb-submitter && ./scripts/build_platform_images.sh -p test'

workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - build:
          requires:
            - test
