version: 2
jobs:
  test:
    working_directory: ~/circle
    docker:
      - image: circleci/ruby:2.6.4
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: lint
          command: docker-compose run --rm app bundle exec rubocop
      - run:
          name: security
          command: docker-compose run --rm app bundle exec brakeman -q --no-pager
      - run:
          name: test
          command: docker-compose run --rm app bundle exec rspec
  build_and_deploy_to_test:
    working_directory: ~/circle/git/fb-submitter
    docker: &ecr_image
      - image: $AWS_BUILD_IMAGE_ECR_ACCOUNT_URL
        aws_auth:
          aws_access_key_id: $AWS_BUILD_IMAGE_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_BUILD_IMAGE_SECRET_ACCESS_KEY
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys:
          fingerprints:
            - "5d:c8:80:1b:1a:82:af:e0:30:26:d1:62:37:7e:c9:c1"
      - run:
          name: Setup base environment variable
          command: |
            echo "export BUILD_SHA=$CIRCLE_SHA1" >> $BASH_ENV
            echo "export SSH_FILE_FOR_SECRETS=~/.ssh/id_rsa_5dc8801b1a82afe03026d162377ec9c1" >> $BASH_ENV
      - run:
          name: cloning deploy scripts
          command: 'git clone git@github.com:ministryofjustice/fb-deploy.git deploy-scripts'
      - run:
          name: build and push docker images
          environment:
            ENVIRONMENT_NAME: test
          command: './deploy-scripts/bin/build'
      - run:
          name: deploy to test dev
          environment:
            APPLICATION_NAME: fb-submitter
            PLATFORM_ENV: test
            DEPLOYMENT_ENV: dev
            K8S_NAMESPACE: formbuilder-platform-test-dev
          command: './deploy-scripts/bin/deploy'
      - run:
          name: deploy to test production
          environment:
            APPLICATION_NAME: fb-submitter
            PLATFORM_ENV: test
            DEPLOYMENT_ENV: production
            K8S_NAMESPACE: formbuilder-platform-test-production
          command: './deploy-scripts/bin/deploy'
  build_and_deploy_to_live:
    working_directory: ~/circle/git/fb-submitter
    docker: *ecr_image
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys:
          fingerprints:
            - "5d:c8:80:1b:1a:82:af:e0:30:26:d1:62:37:7e:c9:c1"
      - run:
          name: Setup base environment variable
          command: |
            echo "export BUILD_SHA=$CIRCLE_SHA1" >> $BASH_ENV
            echo "export SSH_FILE_FOR_SECRETS=~/.ssh/id_rsa_5dc8801b1a82afe03026d162377ec9c1" >> $BASH_ENV
      - run:
          name: cloning deploy scripts
          command: 'git clone git@github.com:ministryofjustice/fb-deploy.git deploy-scripts'
      - run:
          name: build and push docker images
          environment:
            ENVIRONMENT_NAME: live
          command: './deploy-scripts/bin/build'
      - run:
          name: deploy to live dev
          environment:
            APPLICATION_NAME: fb-submitter
            PLATFORM_ENV: live
            DEPLOYMENT_ENV: dev
            K8S_NAMESPACE: formbuilder-platform-live-dev
          command: './deploy-scripts/bin/deploy'
      - run:
          name: deploy to live production
          environment:
            APPLICATION_NAME: fb-submitter
            PLATFORM_ENV: live
            DEPLOYMENT_ENV: production
            K8S_NAMESPACE: formbuilder-platform-live-production
          command: './deploy-scripts/bin/deploy'
  trigger_acceptance_tests:
    working_directory: ~/circle/git/fb-submitter
    docker: *ecr_image
    steps:
      - run:
          name: cloning deploy scripts
          command: 'git clone git@github.com:ministryofjustice/fb-deploy.git deploy-scripts'
      - run:
          name: "Trigger Acceptance Tests"
          command: './deploy-scripts/bin/acceptance_tests'

workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - build_and_deploy_to_test:
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - trigger_acceptance_tests:
          requires:
            - build_and_deploy_to_test
          filters:
            branches:
              only: master
      - confirm_live_deploy:
          type: approval
          requires:
            - trigger_acceptance_tests
      - build_and_deploy_to_live:
          requires:
            - confirm_live_deploy
